---
image: docker:19.03.1

services:
  - docker:19.03.1-dind

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: build
  script:
    - ls prod
  artifacts:
    paths:
      - prod
  only:
    - tags

deploy_to_production:
  stage: deploy
  environment: production
  only:
    - tags
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - apk add --update curl && rm -rf /var/cache/apk/*
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME --tag $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - echo "Will notify update to '{"name":"'"$CI_REGISTRY_IMAGE"'", "tag":"'"$CI_COMMIT_REF_NAME"'"}'"
    - curl --header "Content-Type:application/json" --request POST --data '{"name":"'"$CI_REGISTRY_IMAGE"'", "tag":"'"$CI_COMMIT_REF_NAME"'"}' $API_DEPLOY_WEBHOOK
